# Generated by Django 2.2.1 on 2019-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='nb_people',
        ),
        migrations.AddField(
            model_name='preparation',
            name='calories',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='preparation',
            name='duration',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='preparation',
            name='nb_people',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
