# Generated by Django 2.2.1 on 2019-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190515_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
